def info(*args, **kwargs) -> None: ...
def warning(*args, **kwargs) -> None: ...
def debug(*args, **kwargs) -> None: ...
def debugbold(*args, **kwargs) -> None: ...
def bold(*args, **kwargs) -> None: ...
def bolddim(*args, **kwargs) -> None: ...
def boldalt(*args, **kwargs) -> None: ...
def underline(*args, **kwargs) -> None: ...
def inverse(*args, **kwargs) -> None: ...
def setfg(r: float, g: float, b: float): ...
def setbg(r: float, g: float, b: float): ...
def clear() -> None: ...
