from typing import Any, Dict, Tuple

# /Users/lucaswoj/Code/pal/stubs/mlx_lm.pyi


def load(model_name: str, tokenizer_config: Dict[str, Any] = {}) -> Tuple[Any, Any]: ...
def generate(model: Any, tokenizer: Any, prompt: str, verbose: bool = False) -> str: ...
from typing import Any, Dict, List, Tuple, Optional

def convert(repo: str, quantize: bool = False, upload_repo: Optional[str] = None) -> None: ...
def stream_generate(model: Any, tokenizer: Any, prompt: str, max_tokens: int = 512) -> Any: ...
